/**
 *
 *  drowave_v1_Users.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
using namespace drogon;
namespace drowave
{
namespace v1
{
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r drowave::v1::Users).
 * this class is a restful API controller.
 */
class Users : public drogon::HttpController<Users>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    METHOD_ADD(Users::getOne, "/{1}", Get, Options);
    METHOD_ADD(Users::get, "", Get, Options);
    METHOD_ADD(Users::create, "", Post, Options);
    METHOD_ADD(Users::updateOne, "/{1}", Put, Options);
    // METHOD_ADD(Users::update,"",Put,Options);
    METHOD_ADD(Users::deleteOne, "/{1}", Delete, Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback, std::string &&id);
    void updateOne(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback,
                   std::string &&id);
    void deleteOne(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback,
                   std::string &&id);
    void get(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);

    //    void update(const HttpRequestPtr &req,
    //                std::function<void(const HttpResponsePtr &)> &&callback);
};
} // namespace v1
} // namespace drowave
